build_platform:
  # linux_aarch64: linux_64
  # linux_ppc64le: linux_64
  osx_arm64: osx_64
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  # technically aarch64 has 80 cores?
  linux_aarch64: travis
  # This has 8 cores
  linux_ppc64le: travis
  win: azure
test_on_native_only: true
