# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

version: 2

jobs:
  build_linux_aarch64_:
    working_directory: ~/test
    machine:
      - image: ubuntu-2004:current
    resource_class: arm.large
    environment:
      - CONFIG: "linux_aarch64_"
      - UPLOAD_PACKAGES: "True"
        DOCKER_IMAGE: "quay.io/condaforge/linux-anvil-aarch64"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: |
            export CI=circle
            export FEEDSTOCK_NAME=$(basename ${CIRCLE_PROJECT_REPONAME})
            if [[ "${CIRCLE_PR_NUMBER:-}" == "" ]]; then
              export IS_PR_BUILD="False"
            else
              export IS_PR_BUILD="True"
            fi
            ./.scripts/run_docker_build.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_linux_aarch64_
